const mongoose = require("mongoose");

const HospitalCTSchema = new mongoose.Schema({
    Site: String,
    val_2007_Mean_Wait: {type: Number, required: false},
    val_2007_Median_Wait: {type: Number, required: false},
    val_2007_90th_Percentile_Wait: {type: Number, required: false},
    val_2008_Mean_Wait: {type: Number, required: false},
    val_2008_Median_Wait: {type: Number, required: false},
    val_2008_90th_Percentile_Wait: {type: Number, required: false},
    val_2009_Mean_Wait: {type: Number, required: false},
    val_2009_Median_Wait: {type: Number, required: false},
    val_2009_90th_Percentile_Wait: {type: Number, required: false},
    val_2010_Mean_Wait: {type: Number, required: false},
    val_2010_Median_Wait: {type: Number, required: false},
    val_2010_90th_Percentile_Wait: {type: Number, required: false},
    val_2011_Mean_Wait: {type: Number, required: false},
    val_2011_Median_Wait: {type: Number, required: false},
    val_2011_90th_Percentile_Wait: {type: Number, required: false},
    val_2012_Mean_Wait: {type: Number, required: false},
    val_2012_Median_Wait: {type: Number, required: false},
    val_2012_90th_Percentile_Wait: {type: Number, required: false},
    val_2013_Mean_Wait: {type: Number, required: false},
    val_2013_Median_Wait: {type: Number, required: false},
    val_2013_90th_Percentile_Wait: {type: Number, required: false},
    val_2014_Mean_Wait: {type: Number, required: false},
    val_2014_Median_Wait: {type: Number, required: false},
    val_2014_90th_Percentile_Wait: {type: Number, required: false},
    val_2015_Mean_Wait: {type: Number, required: false},
    val_2015_Median_Wait: {type: Number, required: false},
    val_2015_90th_Percentile_Wait: {type: Number, required: false},
    val_2016_Mean_Wait: {type: Number, required: false},
    val_2016_Median_Wait: {type: Number, required: false},
    val_2016_90th_Percentile_Wait: {type: Number, required: false},
    val_2017_Mean_Wait: {type: Number, required: false},
    val_2017_Median_Wait: {type: Number, required: false},
    val_2017_90th_Percentile_Wait: {type: Number, required: false},
    val_2018_Mean_Wait: {type: Number, required: false},
    val_2018_Median_Wait: {type: Number, required: false},
    val_2018_90th_Percentile_Wait: {type: Number, required: false},
    val_2019_Mean_Wait: {type: Number, required: false},
    val_2019_Median_Wait: {type: Number, required: false},
    val_2019_90th_Percentile_Wait: {type: Number, required: false},
    val_2020_Mean_Wait: {type: Number, required: false},
    val_2020_Median_Wait: {type: Number, required: false},
    val_2020_90th_Percentile_Wait: {type: Number, required: false},
    val_2021_Mean_Wait: {type: Number, required: false},
    val_2021_Median_Wait: {type: Number, required: false},
    val_2021_90th_Percentile_Wait: {type: Number, required: false},
    val_2022_Mean_Wait: {type: Number, required: false},
    val_2022_Median_Wait: {type: Number, required: false},
    val_2022_90th_Percentile_Wait: {type: Number, required: false},
    val_2023_Mean_Wait: {type: Number, required: false},
    val_2023_Median_Wait: {type: Number, required: false},
    val_2023_90th_Percentile_Wait: {type: Number, required: false},
},
{
    timestamps: true
});

const HospitalCT = mongoose.model('HospitalCT', HospitalCTSchema)

module.exports = HospitalCT;